# Site settings
title: "Onur Özüduru"
email:
description: "Personal Blog"
baseurl: ""
url: "http://ozuduru.com"
title_description: "<div><b>Leave the machines alone, they can do it!</b></div><br>I am a <i>Computer Science Junkie, Learner, Dreamer, Slave of My Curiosity, Math Lover, Human, Student Forever</i><br>...And I <i> Want to Become A Machine Trainer, Hate Labelling People</i>"
title_image: ""
disqus_account: "ozuduru"
github_repository: https://github.com/onurozuduru/onurozuduru.github.io
addthis_id: ra-5605bfe8327423c8
post_limit: 3

# Social usernames/URLs
twitter_username: onurozuduru
github_username: onurozuduru
linkedin_link: https://linkedin.com/in/onurozuduru/
tumblr_link: http://onurozuduru.tumblr.com/
google_plus_link: https://plus.google.com/u/0/103922962026531123434
stackoverflow_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> using <a href=\"https://jekyllrb.com/\" target=\"_blank\">Jekyll</a> and theme by <a href=\"https://twitter.com/_JacobTomlinson\" target=\"_blank\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/onurozuduru/onurozuduru.github.io\" target=\"_blank\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
kramdown:
    input: GFM
gems:
  - jekyll-sitemap
permalink: pretty
exclude: [vendor]
